spring:
#    profiles:
#        active: dev
#    http:
#        multipart:
#            maxFileSize: 4096MB
#            maxRequestSize: 4096MB
    jpa:
        database: MYSQL
        # Show or not log for each sql query
        show-sql: false
        hibernate:
            # Hibernate ddl auto (create, create-drop, update): with "update" the database
            # schema will be automatically updated accordingly to java entities found in
            # the project
            ddl-auto: none
            properties:
                hibernate:
                    dialect: org.hibernate.dialect.Oracle10gDialect
        datasource:
            platform: oracle
            driver-class-name: oracle.jdbc.driver.OracleDriver
            # Keep the connection alive if idle for a long time (needed in production)
            testWhileIdle: true
            validationQuery: SELECT 1 from DUAL
    mvc:
        favicon:
            enabled: false

    datasource:
        url: jdbc:mysql://localhost:3306/world_cup?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: Aa123456
        driver-class-name: com.mysql.jdbc.Driver


server:
    port: ${PORT:7777}

#logging:
#    file: logs/${spring.application.name}.log
#    level:
#        ROOT: INFO

#Upgrade properties (using flyway)
#flyway:
#    enabled: true
#    baseline-on-migrate: true
#    table: SM_FLYWAY_VERSION_MS
#    locations: classpath:db/migration
#    sqlMigrationPrefix: sm_v
#    validateOnMigrate: false